name: create release

on:
  workflow_dispatch:

jobs:
  bump-sec-scanners-config:
    name: "bump the sec-scanners-config"
    uses: friedrichwilken/reusable-workflows/.github/workflows/bump-sec-scanners-config-reusable.yml@main
    with:
      actor: "${{ github.actor }}"
    secrets: inherit
