name: Create release

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        type: boolean
        default: false
        description: "Dry run: setting this to `true` will skip the final step of publishing the release, leaving it as a draft-release. This can be helpful for testing and debugging. Note that the tag and release are still getting generated and the next run of this result in incremented release version. To avoid this, do not forget to delete the resulting release and tag."

jobs:
  gen-version:
    name: Generate semantic version from branch and tags
    uses: friedrichwilken/reusable-workflows/.github/workflows/get-version-from-release-branch-reusable.yml@main

    # outputs: VERSION

  bump-sec-scanners-config:
    name: Bump the sec-scandners-config.yaml
    needs: gen-version
    uses: friedrichwilken/reusable-workflows/.github/workflows/bump-sec-scanners-config-reusable.yml@main
    with:
      VERSON: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

  run-unit-test:
    name: Run Unit Tests
    needs: [gen-version, bump-sec-scanners-config]
    uses: friedrichwilken/reusable-workflows/.github/workflows/unit-test-reusable.yml@main

  run-golint-cli:
    name: Run Golint-cli
    needs: [gen-version, bump-sec-scanners-config]
    uses: friedrichwilken/reusable-workflows/.github/workflows/lint-reusable.yml@main

  # todo add step to create a new tag
  # todo add e2e-upgrade testing

  create-draft-release:
    name: Create a draft release
    needs: [run-unit-test, run-golint-cli]
    uses: friedrichwilken/reusable-workflows/.github/workflows/create-draft-release-reusable.yml@main
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  render-and-upload-manifest:
    name: Render and upload the manifests
    needs: [create-draft-release]
    uses: friedrichwilken/reusable-workflows/.github/workflows/render-and-upload-manifests-reusbale.yml@main
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
      CR_FILE: "somedir/cr_file.yaml"
      CRD_FILE: "crd_file.yaml"
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

  publish-release:
    if: ${{ !inputs.DRY_RUN }}
    needs: [render-and-upload-manifests]
    name: Publish the release
    uses: friedrichwilken/reusable-workflows/.github/workflows/publish-release-reusable.yml@main
    with:
      VERSION: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
