name: create release

on:
  workflow_dispatch:

jobs:
  get-user:
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    name: get user
    runs-on: ubuntu-latest
    steps:
      - name: get user name
        shell: bash
        run: echo "$GITHUB_CONTEXT"

  bump-sec-scanners-config:
    name: "bump the sec-scanners-config"
    uses: friedrichwilken/reusable-workflows/.github/workflows/bump-sec-scanners-config-reusable.yml@main
