name: Create Release

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        type: boolean
        default: false
        description: "Dry run: setting this to `true` will skip the final step of publishing the release, leaving it as a draft-release. This can be helpful for testing and debugging. Note that the tag and release are still getting generated and the next run of this result in incremented release version. To avoid this, do not forget to delete the resulting release and tag."
    secrets:
      BOT_PAT:
        required: true

jobs:
  gen-version:
    name: generate version number from branch
    uses: friedrichwilken/reusable-workflows/.github/workflows/get-version-from-branch-reusable.yml@main
    # outputs: VERSION

  bump-sec-scanners-config:
    name: bump the sec-scandners-config.yaml
    needs: gen-version
    uses: friedrichwilken/reusable-workflows/.github/workflows/bump-sec-scanners-config.yml@main
    with:
      version_tag: ${{ needs.gen-version.outputs.VERSION }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}

  run-unit-test:
    name: Run Unit Tests
    needs: [gen-version, bump-sec-scanners-config]
    uses: friedrichwilken/reusable-workflows/.github/workflows/unit-test-reusable.yml@main

  run-golint-cli:
    name: Run Golint-cli
    needs: [gen-version, bump-sec-scanners-config]
    uses: friedrichwilken/reusable-workflows/.github/workflows/lint-reusable.yml@main

  #    create-draft-release:
  #    name: Create a draft release

  #    publish-release:
  #    name: Create a draft release
