name: create release

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        type: boolean
        required: true
        default: false
        description: Setting this to `true` will skip the final step of publishing the release, leaving it as a draft-release. This can be helpful for testing and debugging. Note that the tag and release are still getting generated and the next run of this result in incremented release version. To avoid this, do not forget to delete the resulting release and tag.

jobs:
  create-release:
    name: "create a release"
    uses: friedrichwilken/reusable-workflows/.github/workflows/create-release-reusable.yml@main
    with:
      DRY_RUN: ${{ inputs.DRY_RUN }}
    secrets:
      BOT_PAT: ${{ secrets.BOT_PAT }}
